import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";
import TopNav from "@/components/navbar/TopNavGlass";
import { auth } from "@/auth";
import NextTopLoader from "nextjs-toploader";

// Root layout reads auth session — must be dynamic on every request
export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: "Friends Maker",
  description:
    "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const userId =
    session?.user?.id || null;
  const profileComplete = session?.user
    .profileComplete as boolean;
  return (
    <html lang="en">
      <body>
        <NextTopLoader color="#e11d48" showSpinner={false} />
        <Providers
          profileComplete={
            profileComplete
          }
          userId={userId}
        >
          <TopNav />
          <main className="container mx-auto">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
